name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Npm link html-dom-storage
      - name: Link package
        run: npm link html-dom-storage

      # Run tests
      - name: Run tests
        run: npm test

      # Ensure the package builds correctly
      - name: Run build
        run: npm run build
